#!/bin/ksh
#
# $OpenBSD: unbound,v 1.5 2018/01/11 21:09:26 rpe Exp $

# Modified version of built-in Unbound rc.d script for Unbound version with Python Module support

daemon="/usr/local/sbin/unbound"
daemon_flags="-c /var/unbound/etc/pfui_unbound.conf"
#daemon_user="_unbound"  # TODO: run pfui_unbound with _unbound

. /etc/rc.d/rc.subr

pexp="/usr/local/sbin/unbound ${daemon_flags}"

rc_pre() {
	if grep '^[[:space:]]*auto-trust-anchor-file:' \
            /var/unbound/etc/pfui_unbound.conf > /dev/null 2>&1; then
		/usr/local/sbin/unbound-anchor -v || true
	fi
}

rc_start() {
	/usr/local/sbin/unbound-checkconf /var/unbound/etc/pfui_unbound.conf
	echo ${rcexec}
	/usr/local/sbin/unbound-checkconf /var/unbound/etc/pfui_unbound.conf > /dev/null &&
	    ${rcexec} "/usr/local/sbin/unbound ${daemon_flags}"
}

rc_cmd $1
